services:
  n8n-edu1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-edu1
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin1
      - N8N_BASIC_AUTH_PASSWORD=pass1
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE_FILENAME=/home/node/.n8n/database.sqlite
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
    volumes:
      - ./n8n-edu1:/home/node/.n8n
      - ./daily-data:/data
    networks:
      - n8n-network

  crawl4ai:
    image: unclecode/crawl4ai
    container_name: crawl4ai
    ports:
      - "11235:11235"
    volumes:
      - ./daily-data:/data
    networks:
      - n8n-network

  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite
    volumes:
      - ./daily-data:/data
    networks:
      - n8n-network
    entrypoint: /bin/sh
    command: -c "tail -f /dev/null"

networks:
  n8n-network:
    driver: bridge

volumes:
  daily-data:
